import { Player } from "@lottiefiles/react-lottie-player";
import { Link } from "react-router-dom";

const WelcomePage = () => {
  return (
    <div className="bg-[#ce8cef] min-h-screen ">
      <h1 className="lg:text-4xl text-center font-bold  bg-clip-text text-transparent bg-gradient-to-r from-[#02B7D7] to-[#FF4500]">
  Welcome to our earning platform
</h1> 
      

      <div className="lg:flex items-center justify-center mt-10  lg:pr-10 lg:pl-10">
        <div>
          <h1 className="lg:text-5xl text-[#743f8f] font-bold ">
            MANAGE YOUR <br /> <span className="text-4xl text-[#743f8f]">DASHBOARD</span>
          </h1>
          <p>Income from micro-earning is generated by completing small tasks. These tasks include taking surveys, watching videos, reading emails, data entry, website testing, or sharing on social media. By using various micro-earning platforms, you can easily earn money from home by completing these simple tasks.</p>
          <Link to ='/' className="btn lg:btn-wide bg-[#743f8f] text-white text-xl mt-5">Back to home</Link>
        </div>
        <div className="flex-1 lg:hidden">
          <Player
            autoplay
            loop
            src="https://lottie.host/fc5cc72a-9b5e-44e9-b2ac-b4ddb7f575ff/mvzy4d9kQi.json"
            style={{ height: "300px", width: "200px" }}
          ></Player>
        </div>
        <div className="lg:flex hidden">
          <Player
            autoplay
            loop
            src="https://lottie.host/fc5cc72a-9b5e-44e9-b2ac-b4ddb7f575ff/mvzy4d9kQi.json"
            style={{ height: "600px", width: "600px" }}
          ></Player>
        </div>
      </div>
    </div>
  );
};

export default WelcomePage;
